### ISSUE TITLE
Мой отчет о результатах комита

### ISSUE THREAD

**Issue by ISp1rit** [ISp1rit/FirstProject#1]
Я создал папку ISpirit Project, в ней создал файл K13-1 Моисеев Ярослав Ростиславович.txt с текстом. С помощью Git Bush выполнил следующие команды: 
git init
git add .
git commit -m "first commit"
git remote add origin https://github.com/ISp1rit/ewfwe.git
git push -u origin master
Вот скрины: 
![local storage](https://cloud.githubusercontent.com/assets/17886232/15634249/018b6a24-25c8-11e6-864c-b3615fc6a904.jpg)
![commit](https://cloud.githubusercontent.com/assets/17886232/15634250/018ed9c0-25c8-11e6-9eef-1a322a02c71b.jpg)

**Comment by Smoktii** [comment]
ок
